//
//  Strings.swift
//  CCal
//
//  Created by Ярослав on 30.04.2023.
//

import Foundation

enum Strings {
    static var welcomeMessage =
"""
CCAL V.0
CONSOLE CALCULATOR IN SWIFT. MIT LICENSE.
BY YAROSLAV SEDYSHEV <JAREKSEDY@ICLOUD.COM>
GITHUB.COM/JAREKSEDY

SUPPORTED OPERATORS: %@

ENTER ARITHMETIC EXPRESSION AND HIT RETURN TO EVALUATE OR HIT RETURN TO EXIT.

"""
}
